version: "2"
services:

  angular:
    hostname: nghost
    build: .
    container_name: ngfront
    restart: "no"
    ports:
      - 4200:80
    networks: 
      mentorondemand:
        aliases: 
          - frontend
    # links:
    #   - "feign:feignhost"

networks: 
  mentorondemand: