version: "2"
services:

  angular:
    hostname: nghost
    build: .
    container_name: ngfront
    restart: "no"
    ports:
      - 4200:80
    networks: 
      mentorondemand:
        aliases: 
          - frontend
    links:
      - "mysql:mysqlhost"
      - "eureka:eurekahost"
    # depends_on:
    #   - mysql
    #   - eureka
    #   - user
    #   - mentor
    #   - training
    #   - payment
    #   - authentification
    #   - feign

networks: 
  mentorondemand: