server:
  port: 8021
  
spring:
   jpa:    
    generate-ddl: true  
    open-in-view: true
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    
   application:
    name: mentorondemand-user 
    
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mentorondemand              # 数据库名称
    username: root
    password: root
    data-username: root
    data-password: root
    platform: mysql    
    data: classpath:data.sql
    continue-on-error: true
    
    
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #Register client into Eureka service list
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka/      
  instance:
    instance-id: mentorondemand-user-8021
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
info: 
  app.name: fsd-mentorondemand
  company.name: www.ibm.com
  build.artifactId: mentorondemand-user-8021
  build.version: 0.0.1-SNAPSHOT

