server:
  port: 80


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 900000

  
feign: 
  hystrix: 
    enabled: false


eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eurekahost:7001/eureka/
      